### PR TITLE
Removes references to deprecated OSes/builders

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by eemperor** [comment]
Diagram needs updating as well.

https://github.com/plus3it/terrafirm/blob/master/architecture.png

**Comment by lorengordon** [comment]
@eemperor I don't seem to have access to the source for the original drawing, unfortunately.

**Review by eemperor — APPROVED** [review]
No biggie.  I'm good with the changes to get the builds updated.

**Comment by lorengordon** [comment]
I've reached out to @YakDriver and will update the drawing separately if I can.

**Pull request merged**
