### PR TITLE
Uses watchmaker build.cmd script to create standalone for windows

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
@plus3it/watchmaker ready for a look. the purpose of this is to ensure that for windows we use the same logic for the standalone builds in terrafirm that we use in the packages we push to s3 and github (we already used the same logic for linux).

**Review by eemperor — APPROVED** [review]
Hopefully this does it!

**Pull request merged**
