### PR TITLE
Defaults to main branch from watchmaker instead of deprecated develop

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Review by eemperor — APPROVED** [review]
🚢

**Comment by lorengordon** [comment]
for the record, `codebuild/default/pr` did succeed, but the github status check didn't post, presumably due to the github issue today: https://www.githubstatus.com/incidents/wdhkj70kynwk

**Pull request merged**
