### PR TITLE
Add instance index to log directory/archive names

### PR DESCRIPTION
**Pull request by YakDriver**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
Oops, no worky. Need to reduce the size of the userdata on Windows. :(

```
* aws_instance.win[0]: expected length of user_data to be in the range (0 - 16384)
```

**Comment by YakDriver** [comment]
I did test it and it _worked_ fine. :unamused:

**Comment by YakDriver** [comment]
This add the instance index, such as win-3, to the log directory
names and zip file names. With this information, it easier to match
up Terraforms reporting with the related S3 artifacts. For example,
Terraform may report an error related to instance win.1 or win[1].
Now the S3 log directory for that instance and the archive file will
include win-1.

**Comment by lorengordon** [comment]
It's probably right on the edge of the max size, and some variable-length calculation pushes it over...

**Comment by YakDriver** [comment]
Yeah, my wordy comments...

**Comment by YakDriver** [comment]
go codebuild go

**Comment by YakDriver** [comment]
That works. It should be quite a few bytes below 16k now so there's some breathing room.

**Comment by lorengordon** [comment]
Works for me, merge at will.

**Pull request merged**
