### PR TITLE
Move to Xenial for Docker compatibility

### PR DESCRIPTION
**Pull request by YakDriver**

### CODE REVIEW

**Comment by YakDriver** [comment]
This change must be made concurrently with the Watchmaker change. Installation of Docker is different on Xenial than Trusty.

**Comment by lorengordon** [comment]
go codebuild go

**Comment by YakDriver** [comment]
Slow/broken webhook. codebuild succeeded 30 minutes ago.

**Comment by YakDriver** [comment]
go codebuild go

**Pull request merged**
