### PR TITLE
Aligns to new standalone build process, without gravitybee

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
There's some cross-dependency between this pr an the related one on watchmaker, https://github.com/plus3it/watchmaker/pull/2557...

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
Codebuild jobs are dependent on https://github.com/plus3it/watchmaker/pull/2561, but I ran one manually, using both this pr and that one to show this fixes things. I'd like to merge this pr, before the watchmaker one.

https://us-east-1.console.aws.amazon.com/codesuite/codebuild/701759196663/projects/terrafirm/build/terrafirm%3Aa68aee63-7ef6-40f0-bee6-a75b30c9ba41?region=us-east-1

**Review by eemperor — APPROVED** [review]

**Pull request merged**
